// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: pkg/proto/transporter.proto

package transporter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelayType int32

const (
	RelayType_HEAVY RelayType = 0
	RelayType_LIGHT RelayType = 1
)

// Enum value maps for RelayType.
var (
	RelayType_name = map[int32]string{
		0: "HEAVY",
		1: "LIGHT",
	}
	RelayType_value = map[string]int32{
		"HEAVY": 0,
		"LIGHT": 1,
	}
)

func (x RelayType) Enum() *RelayType {
	p := new(RelayType)
	*p = x
	return p
}

func (x RelayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_transporter_proto_enumTypes[0].Descriptor()
}

func (RelayType) Type() protoreflect.EnumType {
	return &file_pkg_proto_transporter_proto_enumTypes[0]
}

func (x RelayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayType.Descriptor instead.
func (RelayType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_transporter_proto_rawDescGZIP(), []int{0}
}

type Climate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Dht22Port  uint32 `protobuf:"varint,2,opt,name=dht22_port,json=dht22Port,proto3" json:"dht22_port,omitempty"`
	AqiPort    uint32 `protobuf:"varint,3,opt,name=aqi_port,json=aqiPort,proto3" json:"aqi_port,omitempty"`
	HasBuzzer  bool   `protobuf:"varint,4,opt,name=has_buzzer,json=hasBuzzer,proto3" json:"has_buzzer,omitempty"`
	BuzzerPort uint32 `protobuf:"varint,5,opt,name=buzzer_port,json=buzzerPort,proto3" json:"buzzer_port,omitempty"`
}

func (x *Climate) Reset() {
	*x = Climate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_transporter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Climate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Climate) ProtoMessage() {}

func (x *Climate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transporter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Climate.ProtoReflect.Descriptor instead.
func (*Climate) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transporter_proto_rawDescGZIP(), []int{0}
}

func (x *Climate) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Climate) GetDht22Port() uint32 {
	if x != nil {
		return x.Dht22Port
	}
	return 0
}

func (x *Climate) GetAqiPort() uint32 {
	if x != nil {
		return x.AqiPort
	}
	return 0
}

func (x *Climate) GetHasBuzzer() bool {
	if x != nil {
		return x.HasBuzzer
	}
	return false
}

func (x *Climate) GetBuzzerPort() uint32 {
	if x != nil {
		return x.BuzzerPort
	}
	return 0
}

type Ldr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *Ldr) Reset() {
	*x = Ldr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_transporter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ldr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ldr) ProtoMessage() {}

func (x *Ldr) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transporter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ldr.ProtoReflect.Descriptor instead.
func (*Ldr) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transporter_proto_rawDescGZIP(), []int{1}
}

func (x *Ldr) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ldr) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Motion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Port         uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	RelayId      uint32 `protobuf:"varint,3,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	RelayChannel uint32 `protobuf:"varint,4,opt,name=relay_channel,json=relayChannel,proto3" json:"relay_channel,omitempty"`
}

func (x *Motion) Reset() {
	*x = Motion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_transporter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Motion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Motion) ProtoMessage() {}

func (x *Motion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transporter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Motion.ProtoReflect.Descriptor instead.
func (*Motion) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transporter_proto_rawDescGZIP(), []int{2}
}

func (x *Motion) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Motion) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Motion) GetRelayId() uint32 {
	if x != nil {
		return x.RelayId
	}
	return 0
}

func (x *Motion) GetRelayChannel() uint32 {
	if x != nil {
		return x.RelayChannel
	}
	return 0
}

type Relay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type RelayType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.RelayType" json:"type,omitempty"`
}

func (x *Relay) Reset() {
	*x = Relay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_transporter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Relay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relay) ProtoMessage() {}

func (x *Relay) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transporter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relay.ProtoReflect.Descriptor instead.
func (*Relay) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transporter_proto_rawDescGZIP(), []int{3}
}

func (x *Relay) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Relay) GetType() RelayType {
	if x != nil {
		return x.Type
	}
	return RelayType_HEAVY
}

type ConfigData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version     uint32     `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ClimateSize uint32     `protobuf:"varint,2,opt,name=climate_size,json=climateSize,proto3" json:"climate_size,omitempty"`
	LdrSize     uint32     `protobuf:"varint,3,opt,name=ldr_size,json=ldrSize,proto3" json:"ldr_size,omitempty"`
	MotionSize  uint32     `protobuf:"varint,4,opt,name=motion_size,json=motionSize,proto3" json:"motion_size,omitempty"`
	RelaySize   uint32     `protobuf:"varint,5,opt,name=relay_size,json=relaySize,proto3" json:"relay_size,omitempty"`
	Climates    []*Climate `protobuf:"bytes,8,rep,name=climates,proto3" json:"climates,omitempty"` // Climate config array
	Ldrs        []*Ldr     `protobuf:"bytes,9,rep,name=ldrs,proto3" json:"ldrs,omitempty"`         // LDR config array
	Motions     []*Motion  `protobuf:"bytes,10,rep,name=motions,proto3" json:"motions,omitempty"`  // Motion sensor config array
	Relays      []*Relay   `protobuf:"bytes,11,rep,name=relays,proto3" json:"relays,omitempty"`    // Relay config array
}

func (x *ConfigData) Reset() {
	*x = ConfigData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_transporter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigData) ProtoMessage() {}

func (x *ConfigData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transporter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigData.ProtoReflect.Descriptor instead.
func (*ConfigData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transporter_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigData) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigData) GetClimateSize() uint32 {
	if x != nil {
		return x.ClimateSize
	}
	return 0
}

func (x *ConfigData) GetLdrSize() uint32 {
	if x != nil {
		return x.LdrSize
	}
	return 0
}

func (x *ConfigData) GetMotionSize() uint32 {
	if x != nil {
		return x.MotionSize
	}
	return 0
}

func (x *ConfigData) GetRelaySize() uint32 {
	if x != nil {
		return x.RelaySize
	}
	return 0
}

func (x *ConfigData) GetClimates() []*Climate {
	if x != nil {
		return x.Climates
	}
	return nil
}

func (x *ConfigData) GetLdrs() []*Ldr {
	if x != nil {
		return x.Ldrs
	}
	return nil
}

func (x *ConfigData) GetMotions() []*Motion {
	if x != nil {
		return x.Motions
	}
	return nil
}

func (x *ConfigData) GetRelays() []*Relay {
	if x != nil {
		return x.Relays
	}
	return nil
}

type ClimateSensorData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId    int32   `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Temperature float32 `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity    float32 `protobuf:"fixed32,4,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Aqi         float32 `protobuf:"fixed32,5,opt,name=aqi,proto3" json:"aqi,omitempty"`
}

func (x *ClimateSensorData) Reset() {
	*x = ClimateSensorData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_transporter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClimateSensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClimateSensorData) ProtoMessage() {}

func (x *ClimateSensorData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transporter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClimateSensorData.ProtoReflect.Descriptor instead.
func (*ClimateSensorData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transporter_proto_rawDescGZIP(), []int{5}
}

func (x *ClimateSensorData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClimateSensorData) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *ClimateSensorData) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ClimateSensorData) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *ClimateSensorData) GetAqi() float32 {
	if x != nil {
		return x.Aqi
	}
	return 0
}

type LdrSensorData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId int32   `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LdrValue float32 `protobuf:"fixed32,3,opt,name=ldr_value,json=ldrValue,proto3" json:"ldr_value,omitempty"`
}

func (x *LdrSensorData) Reset() {
	*x = LdrSensorData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_transporter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LdrSensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LdrSensorData) ProtoMessage() {}

func (x *LdrSensorData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transporter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LdrSensorData.ProtoReflect.Descriptor instead.
func (*LdrSensorData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transporter_proto_rawDescGZIP(), []int{6}
}

func (x *LdrSensorData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LdrSensorData) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *LdrSensorData) GetLdrValue() float32 {
	if x != nil {
		return x.LdrValue
	}
	return 0
}

type MotionSensorData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId       int32  `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	MotionDetected bool   `protobuf:"varint,3,opt,name=motion_detected,json=motionDetected,proto3" json:"motion_detected,omitempty"`
}

func (x *MotionSensorData) Reset() {
	*x = MotionSensorData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_transporter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MotionSensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotionSensorData) ProtoMessage() {}

func (x *MotionSensorData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transporter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotionSensorData.ProtoReflect.Descriptor instead.
func (*MotionSensorData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transporter_proto_rawDescGZIP(), []int{7}
}

func (x *MotionSensorData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MotionSensorData) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *MotionSensorData) GetMotionDetected() bool {
	if x != nil {
		return x.MotionDetected
	}
	return false
}

type RelayData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId    int32  `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RelayStatus bool   `protobuf:"varint,3,opt,name=relay_status,json=relayStatus,proto3" json:"relay_status,omitempty"`
}

func (x *RelayData) Reset() {
	*x = RelayData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_transporter_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayData) ProtoMessage() {}

func (x *RelayData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transporter_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayData.ProtoReflect.Descriptor instead.
func (*RelayData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transporter_proto_rawDescGZIP(), []int{8}
}

func (x *RelayData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RelayData) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *RelayData) GetRelayStatus() bool {
	if x != nil {
		return x.RelayStatus
	}
	return false
}

type SensorData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId int32 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Types that are assignable to Data:
	//
	//	*SensorData_Climate
	//	*SensorData_Ldr
	//	*SensorData_Motion
	Data isSensorData_Data `protobuf_oneof:"data"`
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_transporter_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transporter_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transporter_proto_rawDescGZIP(), []int{9}
}

func (x *SensorData) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (m *SensorData) GetData() isSensorData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *SensorData) GetClimate() *ClimateSensorData {
	if x, ok := x.GetData().(*SensorData_Climate); ok {
		return x.Climate
	}
	return nil
}

func (x *SensorData) GetLdr() *LdrSensorData {
	if x, ok := x.GetData().(*SensorData_Ldr); ok {
		return x.Ldr
	}
	return nil
}

func (x *SensorData) GetMotion() *MotionSensorData {
	if x, ok := x.GetData().(*SensorData_Motion); ok {
		return x.Motion
	}
	return nil
}

type isSensorData_Data interface {
	isSensorData_Data()
}

type SensorData_Climate struct {
	Climate *ClimateSensorData `protobuf:"bytes,3,opt,name=climate,proto3,oneof"`
}

type SensorData_Ldr struct {
	Ldr *LdrSensorData `protobuf:"bytes,4,opt,name=ldr,proto3,oneof"`
}

type SensorData_Motion struct {
	Motion *MotionSensorData `protobuf:"bytes,5,opt,name=motion,proto3,oneof"`
}

func (*SensorData_Climate) isSensorData_Data() {}

func (*SensorData_Ldr) isSensorData_Data() {}

func (*SensorData_Motion) isSensorData_Data() {}

type SecurityCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId *string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	DeviceId  string  `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Uid       []byte  `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *SecurityCommand) Reset() {
	*x = SecurityCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_transporter_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityCommand) ProtoMessage() {}

func (x *SecurityCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transporter_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityCommand.ProtoReflect.Descriptor instead.
func (*SecurityCommand) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transporter_proto_rawDescGZIP(), []int{10}
}

func (x *SecurityCommand) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *SecurityCommand) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SecurityCommand) GetUid() []byte {
	if x != nil {
		return x.Uid
	}
	return nil
}

type SecurityStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SecurityStatus) Reset() {
	*x = SecurityStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_transporter_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityStatus) ProtoMessage() {}

func (x *SecurityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transporter_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityStatus.ProtoReflect.Descriptor instead.
func (*SecurityStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transporter_proto_rawDescGZIP(), []int{11}
}

func (x *SecurityStatus) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type RegistrationCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId  string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RequestId string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *RegistrationCommand) Reset() {
	*x = RegistrationCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_transporter_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationCommand) ProtoMessage() {}

func (x *RegistrationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transporter_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationCommand.ProtoReflect.Descriptor instead.
func (*RegistrationCommand) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transporter_proto_rawDescGZIP(), []int{12}
}

func (x *RegistrationCommand) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegistrationCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_pkg_proto_transporter_proto protoreflect.FileDescriptor

var file_pkg_proto_transporter_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x01, 0x0a, 0x07, 0x43, 0x6c, 0x69, 0x6d, 0x61, 0x74, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x68, 0x74, 0x32, 0x32, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x64, 0x68, 0x74, 0x32, 0x32, 0x50, 0x6f, 0x72, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x71, 0x69, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x61, 0x71, 0x69, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61,
	0x73, 0x5f, 0x62, 0x75, 0x7a, 0x7a, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x68, 0x61, 0x73, 0x42, 0x75, 0x7a, 0x7a, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x7a,
	0x7a, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x62, 0x75, 0x7a, 0x7a, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x29, 0x0a, 0x03, 0x4c, 0x64,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x6c, 0x0a, 0x06, 0x4d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x22, 0x3d, 0x0a, 0x05, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0xbf, 0x02, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x6c, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x6c, 0x64, 0x72, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x6c, 0x64, 0x72, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65,
	0x6c, 0x61, 0x79, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x72, 0x65, 0x6c, 0x61, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x63, 0x6c, 0x69,
	0x6d, 0x61, 0x74, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x52, 0x08, 0x63, 0x6c, 0x69,
	0x6d, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x04, 0x6c, 0x64, 0x72, 0x73, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x64, 0x72, 0x52,
	0x04, 0x6c, 0x64, 0x72, 0x73, 0x12, 0x27, 0x0a, 0x07, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d,
	0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x24,
	0x0a, 0x06, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x06, 0x72, 0x65,
	0x6c, 0x61, 0x79, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x6d, 0x61, 0x74, 0x65,
	0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x65,
	0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x75, 0x6d,
	0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x68, 0x75, 0x6d,
	0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x71, 0x69, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x03, 0x61, 0x71, 0x69, 0x22, 0x59, 0x0a, 0x0d, 0x4c, 0x64, 0x72, 0x53, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x64, 0x72, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x64, 0x72, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x68, 0x0a, 0x10, 0x4d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x65,
	0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x6d, 0x6f,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x5b, 0x0a, 0x09,
	0x52, 0x65, 0x6c, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x72, 0x65,
	0x6c, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xc4, 0x01, 0x0a, 0x0a, 0x53, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x6c, 0x69, 0x6d, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6c, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x48, 0x00, 0x52, 0x07, 0x63, 0x6c, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x6c,
	0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4c, 0x64, 0x72, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00,
	0x52, 0x03, 0x6c, 0x64, 0x72, 0x12, 0x31, 0x0a, 0x06, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00,
	0x52, 0x06, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x73, 0x0a, 0x0f, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x75, 0x69, 0x64, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x0e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x51, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x2a, 0x21, 0x0a, 0x09, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x09, 0x0a, 0x05, 0x48, 0x45, 0x41, 0x56, 0x59, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x49,
	0x47, 0x48, 0x54, 0x10, 0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x72, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_transporter_proto_rawDescOnce sync.Once
	file_pkg_proto_transporter_proto_rawDescData = file_pkg_proto_transporter_proto_rawDesc
)

func file_pkg_proto_transporter_proto_rawDescGZIP() []byte {
	file_pkg_proto_transporter_proto_rawDescOnce.Do(func() {
		file_pkg_proto_transporter_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_transporter_proto_rawDescData)
	})
	return file_pkg_proto_transporter_proto_rawDescData
}

var file_pkg_proto_transporter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_transporter_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_proto_transporter_proto_goTypes = []any{
	(RelayType)(0),              // 0: proto.RelayType
	(*Climate)(nil),             // 1: proto.Climate
	(*Ldr)(nil),                 // 2: proto.Ldr
	(*Motion)(nil),              // 3: proto.Motion
	(*Relay)(nil),               // 4: proto.Relay
	(*ConfigData)(nil),          // 5: proto.ConfigData
	(*ClimateSensorData)(nil),   // 6: proto.ClimateSensorData
	(*LdrSensorData)(nil),       // 7: proto.LdrSensorData
	(*MotionSensorData)(nil),    // 8: proto.MotionSensorData
	(*RelayData)(nil),           // 9: proto.RelayData
	(*SensorData)(nil),          // 10: proto.SensorData
	(*SecurityCommand)(nil),     // 11: proto.SecurityCommand
	(*SecurityStatus)(nil),      // 12: proto.SecurityStatus
	(*RegistrationCommand)(nil), // 13: proto.RegistrationCommand
}
var file_pkg_proto_transporter_proto_depIdxs = []int32{
	0, // 0: proto.Relay.type:type_name -> proto.RelayType
	1, // 1: proto.ConfigData.climates:type_name -> proto.Climate
	2, // 2: proto.ConfigData.ldrs:type_name -> proto.Ldr
	3, // 3: proto.ConfigData.motions:type_name -> proto.Motion
	4, // 4: proto.ConfigData.relays:type_name -> proto.Relay
	6, // 5: proto.SensorData.climate:type_name -> proto.ClimateSensorData
	7, // 6: proto.SensorData.ldr:type_name -> proto.LdrSensorData
	8, // 7: proto.SensorData.motion:type_name -> proto.MotionSensorData
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_proto_transporter_proto_init() }
func file_pkg_proto_transporter_proto_init() {
	if File_pkg_proto_transporter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_transporter_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Climate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_transporter_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Ldr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_transporter_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Motion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_transporter_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Relay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_transporter_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_transporter_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ClimateSensorData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_transporter_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*LdrSensorData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_transporter_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*MotionSensorData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_transporter_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*RelayData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_transporter_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SensorData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_transporter_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*SecurityCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_transporter_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*SecurityStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_transporter_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*RegistrationCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_proto_transporter_proto_msgTypes[9].OneofWrappers = []any{
		(*SensorData_Climate)(nil),
		(*SensorData_Ldr)(nil),
		(*SensorData_Motion)(nil),
	}
	file_pkg_proto_transporter_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_transporter_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_transporter_proto_goTypes,
		DependencyIndexes: file_pkg_proto_transporter_proto_depIdxs,
		EnumInfos:         file_pkg_proto_transporter_proto_enumTypes,
		MessageInfos:      file_pkg_proto_transporter_proto_msgTypes,
	}.Build()
	File_pkg_proto_transporter_proto = out.File
	file_pkg_proto_transporter_proto_rawDesc = nil
	file_pkg_proto_transporter_proto_goTypes = nil
	file_pkg_proto_transporter_proto_depIdxs = nil
}
