auth:
  - username: peach
    password: password1
    allow: true
  - username: melon
    password: password2
    allow: true
acl:
  - remote: 127.0.0.1:*
  - username: melon
    filters:
    arduino/#: 0
